<?php
/**
 * Category product list
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
use Magento\Framework\App\Action\Action;

$isWidget = $block instanceof \Magento\CatalogWidget\Block\Product\ProductsList;
$productCollection = $block->getLoadedProductCollection();
?>
<?php if($productCollection->count()): ?>
    <ul class="product-list">
        <?php /** @var \Magento\Catalog\Model\Product $product */ ?>
        <?php foreach($productCollection as $product): ?>
            <?php $url = $product->getProductUrl(); ?>
            <?php $name = $product->getName(); ?>
            <li>
                <div class="wrap">
                    <?php $image = $block->getImage($product, 'category_page_list') ?>
                    <?php if($url): ?>
                        <div class="image">
                            <a href="<?= $url ?>" title="<?= $name ?>">
                                <?= $image->toHtml() ?>
                            </a>
                        </div>
                        <?= $block->getProductPrice($product) ?>
                        <div class="name">
                            <a href="<?= $url ?>" title="<?= $name ?>"><?= $name ?></a>
                        </div>
                    <?php else: ?>
                        <div class="image">
                            <?= $image->toHtml() ?>
                        </div>
                        <div class="name"><?= $name ?></div>
                    <?php endif; ?>
                    <?php if(!$isWidget): ?>
                        <div class="description">
                            <?= $product->getShortDescription() ?>
                        </div>
                    <?php endif; ?>
                    <?php if($product->isSaleable()): ?>
                        <?php $postParams = $block->getAddToCartPostParams($product); ?>
                        <form action="<?= $postParams['action'] ?>" method="post" class="to-cart">
                            <input type="hidden" name="product" value="<?= $postParams['data']['product'] ?>" />
                            <input type="hidden" name="<?= Action::PARAM_NAME_URL_ENCODED ?>" value="<?= $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>" />
                            <?= $block->getBlockHtml('formkey') ?>
                            <button class="action tocart large" title="<?= __('Add to Cart') ?>">
                                <span><?= __('Add to Cart') ?></span>
                            </button>
                        </form>
                    <?php endif; ?>
                    <?php if($addToBlock = $block->getChildBlock('addto')): ?>
                        <div class="addto">
                            <?= $addToBlock->setProduct($product)->getChildHtml() ?>
                        </div>
                    <?php endif; ?>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
    <script type="text/x-magento-init">
    {
        ".product-list .to-cart": {
            "catalogAddToCart": {
                "addToCartButtonTextAdded": "<?= __('Adding...') ?>",
                "minicartSelector": "header .cart"
            }
        }
    }
    </script>
<?php endif; ?>
