<?php

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<form class="search" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>">
    <input
            type="text"
            name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
            value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
            maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
    />
    <button><?php echo $block->escapeHtml(__('Search')) ?></button>
</form>
