<?php
/**
 * Search form in header
 *
 * @var $block \Magento\Framework\View\Element\Template
 * @var $helper \Magento\Search\Helper\Data
 */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<form class="search" action="<?= $helper->getResultUrl() ?>">
    <input
            type="text"
            name="<?= $helper->getQueryParamName() ?>"
            value="<?= $helper->getEscapedQueryText() ?>"
            maxlength="<?= $helper->getMaxQueryLength() ?>"
    />
    <button><?= $block->escapeHtml(__('Search')) ?></button>
</form>
