<?php
/**
 * Minicart block in header
 *
 * @var $this \Magento\Framework\View\TemplateEngine\Php
 * @var $block \Magento\Checkout\Block\Cart\Sidebar
 */

/** @var \Magento\Framework\Json\Helper\Data $jsonHelper */
$jsonHelper = $this->helper('Magento\Framework\Json\Helper\Data');

$config = $block->getConfig();
unset($config['updateItemQtyUrl']);
unset($config['removeItemUrl']);
unset($config['imageTemplate']);
unset($config['isRedirectRequired']);
unset($config['autocomplete']);
unset($config['captcha']);
?>
<div class="cart" data-block="minicart">
    <a href="#" data-bind="scope: 'minicart_content'">
        <span class="block">
            <h3><?= __('My Cart') ?></h3>
            <span class="action toggle">
                <!-- ko text: getCartParam('summary_label') --><!-- /ko -->
                <!-- ko if: getCartParam('subtotal') -->
                    <span data-bind="html: ' — '+getCartParam('subtotal')"></span>
                <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if($block->getIsNeedToDisplaySideBar()): ?>
        <div class="sidebar cart-sidebar" data-bind="scope: 'minicart_content'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
        <script type="text/x-magento-init">
        {
            "header .sidebar": {
                "dropdownDialog": {
                    "appendTo": "header .cart",
                    "triggerTarget": "header .cart > a",
                    "closeOnMouseLeave": false,
                    "parentClass": "active",
                    "triggerClass": "active",
                    "buttons": []
                }
            }
        }
        </script>
    <?php endif; ?>
</div>
<script>
    window.checkout = <?= $jsonHelper->jsonEncode($config) ?>;
</script>
<script type="text/x-magento-init">
{
    "[data-block=\"minicart\"]": {
        "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>,
        "loader": {}
    }
}
</script>
