<?php
/**
 * Minicart block in header
 *
 * @var $block \Magento\Checkout\Block\Cart\Sidebar
 */
?>
<div class="cart">
    <h3><?= __('My Cart') ?></h3>
    <div class="summary action toggle" data-bind="scope: 'minicart_content'">
        <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
        <?php if($block->getCurrentStoreLocale() == 'ru_RU'): ?>
            <!-- ko text: getLabel(getCartParam('summary_count'), ['<?= __('item1') ?>', '<?= __('item2') ?>', '<?= __('item3') ?>']) --><!-- /ko -->
        <?php else: ?>
            <!-- ko if: getCartParam('summary_count') == 1 -->
                <!-- ko i18n: 'item' --><!-- /ko -->
            <!-- /ko -->
            <!-- ko ifnot: getCartParam('summary_count') == 1 -->
                <!-- ko i18n: 'items' --><!-- /ko -->
            <!-- /ko -->
        <?php endif; ?>
        <span data-bind="html: ' — '+getCartParam('subtotal')"></span>
    </div>
    <?php if($block->getIsNeedToDisplaySideBar()): ?>
        <div class="sidebar" data-bind="scope: 'minicart_content'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
        <script type="text/x-magento-init">
        {
            "header .cart .sidebar": {
                "dropdownDialog": {
                    "appendTo": "header .cart",
                    "triggerTarget": "header .cart .summary",
                    "closeOnMouseLeave": false,
                    "parentClass": "active",
                    "triggerClass": "active",
                    "buttons": []
                }
            }
        }
        </script>
    <?php endif; ?>
</div>
<script>
    window.checkout = <?= \Zend_Json::encode($block->getConfig()) ?>;
</script>
<script type="text/x-magento-init">
{
    "header .cart *": {
        "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
    }
}
</script>
