<?php
/**
 * Minicart sidebar block
 *
 * @var $block \Magento\Checkout\Block\Cart\Sidebar
 */

$jsPhrases = [
    $block->escapeJsQuote(__('There is <a href=\'%1\'>%2</a> in your cart.')),
    $block->escapeJsQuote(__('There are <a href=\'%1\'>%2</a> in your cart.'))
];
?>
<div class="block cart-sidebar" data-block="minicart" data-bind="scope: 'minicart_content'">
    <h2><?= __('My Cart') ?></h2>
    <!-- ko if: getCartParam('summary_count') -->
        <span class="summary"
              data-bind="html: (getCartParam('summary_count') == 1 ? '<?= $jsPhrases[0] ?>' : '<?= $jsPhrases[1] ?>')
                               .replace('%1', shoppingCartUrl).replace('%2', getCartParam('summary_label'))">
        </span>
        <!-- ko template: getTemplate() --><!-- /ko -->
    <!-- /ko -->
    <!-- ko ifnot: getCartParam('summary_count') -->
        <span data-bind="text: '<?= __('You have no items in your shopping cart.') ?>'"></span>
    <!-- /ko -->
</div>
