<?php
/**
 * Currency switcher
 *
 * @var $block \Magento\Directory\Block\Currency
 * @see \IdealCode\Directory\Block\Currency
 */
?>
<?php if ($block->getCurrencyCount() > 1): ?>
    <div class="switcher switcher-currency">
        <a href="#" class="action toggle"><?= $block->getCurrentCurrencySymbol() ?></a>
        <ul class="dropdown"
            data-mage-init='{"dropdownDialog":{
                "appendTo": ".switcher-currency",
                "triggerTarget": ".switcher-currency .toggle",
                "closeOnMouseLeave": false,
                "parentClass": "active",
                "triggerClass": "active",
                "buttons": []
            }}'>
            <?php foreach ($block->getCurrencies() as $_code => $_name): ?>
                <li><a href="#" data-post='<?= $block->getSwitchCurrencyPostData($_code) ?>'><?= $_name ?> - <?= $_code ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
