<?php
/**
 * Viewed products block in sidebar
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<div data-bind="scope: 'viewedProducts'">
    <div class="block viewed" data-bind="visible: viewedProducts().items && viewedProducts().items.length" style="display: none;">
        <h2><?= __('Viewed Products') ?></h2>
        <ul data-bind="foreach: viewedProducts().items">
            <li>
                <!-- ko if: url -->
                    <a class="link" data-bind="attr: {href: url, title: name}, text: name"></a>
                <!-- /ko -->
                <!-- ko ifnot: url -->
                    <span class="link" data-bind="text: name"></span>
                <!-- /ko -->
            </li>
        </ul>
    </div>
</div>
