<?php
/**
 * Viewed products block in sidebar
 */
?>
<div data-bind="scope: 'viewedProducts'">
    <div class="block viewed" data-bind="visible: viewedProducts().items && viewedProducts().items.length" style="display: none;">
        <h2><?= __('Viewed Products') ?></h2>
        <ul data-bind="foreach: viewedProducts().items">
            <li>
                <!-- ko if: url -->
                    <a class="name" data-bind="attr: {href: url, title: name}, text: name"></a>
                <!-- /ko -->
                <!-- ko ifnot: url -->
                    <span class="name" data-bind="text: name"></span>
                <!-- /ko -->
            </li>
        </ul>
    </div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "viewedProducts": {
                    "component": "IdealCode_CatalogViewed/js/view/viewed-products"
                }
            }
        }
    }
}
</script>
