<?php
/**
 * Logo block in header
 *
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<a href="<?= $block->getUrl('') ?>" title="<?= $storeName ?>" class="logo">
    <img src="<?= $block->getLogoSrc() ?>" alt="<?= $block->getLogoAlt() ?>"
         <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
         <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
    />
</a>
