<?php
/**
 * Product list block
 *
 * @var $block \Magento\Catalog\Block\Product\AbstractProduct
 */
if(method_exists($block, 'getItemCollection')) {
    $block->setLoadedProductCollection($block->getItemCollection());
} elseif(method_exists($block, 'getItems')) {
    $block->setLoadedProductCollection($block->getItems());
}

$block->setBaseImageId('small_products_list_base');
$block->setSecondImageId('small_products_list_second');

include($block->getTemplateFile('Magento_Catalog::product/list.phtml'));
