<?php
/**
 * Product list toolbar
 *
 * @var $this \Magento\Framework\View\TemplateEngine\Php
 * @var $block \IdealCode\Catalog\Block\Product\ProductList\Toolbar
 */

/** @var \IdealCode\Catalog\Helper\Data $helper */
$helper = $this->helper('IdealCode\Catalog\Helper\Data');
?>
<p class="amount">
    <?php if($block->getLastPageNum() > 1): ?>
        <?php if($block->getFirstNum() == $block->getLastNum()): ?>
            <?= __('Item %1 of %2', $block->getFirstNum(), $block->getTotalNum()) ?>
        <?php else: ?>
            <?= __('Items %1-%2 of %3', $block->getFirstNum(), $block->getLastNum(), $block->getTotalNum()) ?>
        <?php endif; ?>
    <?php else: ?>
        <?= $helper->getAmountLabel($block->getTotalNum()) ?>
    <?php endif; ?>
</p>
