<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
$limitParamName = \IdealCode\Catalog\Model\Product\ProductList\Toolbar::LIMIT_PARAM_NAME;
?>
<div class="limiter">
    <label><?= __('Show by:') ?></label>
    <select>
        <?php foreach($block->getAvailableLimit() as $key => $limit): ?>
            <option value="<?= $block->getPagerUrl([$limitParamName => $key]) ?>"
                <?= $block->isLimitCurrent($key) ? ' selected' : '' ?>>
                <?= $limit ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>
