<?php
/**
 * Subscribe news block
 *
 * @var $block \Magento\Newsletter\Block\Subscribe
 */
?>
<form class="newsletter" action="<?= $block->getFormActionUrl() ?>">
    <label><?= __('Sign Up for Our Newsletter:') ?></label>
    <div class="row">
        <div class="cell">
            <input type="text" />
        </div>
        <div class="cell">
            <button><?= __('Subscribe') ?></button>
        </div>
    </div>
</form>
