<?php
/**
 * Add to compare link in product list
 *
 * @var $this \Magento\Framework\View\TemplateEngine\Php
 * @var $block \Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare
 */

/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getProduct();
/** @var \Magento\Catalog\Helper\Product\Compare $helper */
$helper = $this->helper('Magento\Catalog\Helper\Product\Compare');
?>
<div data-bind="scope: 'compareProducts'">
    <!-- ko ifnot: productInCompare('<?= $product->getId() ?>') -->
        <a href="#"
           title="<?= __('Add to Compare') ?>"
           data-bind="attr: {class: 'compare-action'}, text: '<?= __('Add to Compare') ?>'"
           data-ajax='<?= $helper->getPostDataParams($product) ?>'>
            &nbsp;
        </a>
    <!-- /ko -->
    <!-- ko if: productInCompare('<?= $product->getId() ?>') -->
    <a href="#"
       title="<?= __('Remove from Compare') ?>"
       data-bind="attr: {class: 'compare-action'}, text: '<?= __('Remove from Compare') ?>'"
       data-ajax='<?= $helper->getPostDataRemove($product) ?>'>
        &nbsp;
    </a>
    <!-- /ko -->
</div>
